# Generated by Django 3.0.7 on 2020-07-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200709_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='meme',
            new_name='memo',
        ),
    ]
